package cr.ac.una.prograiv.moviestar.domain;
// Generated May 8, 2016 3:08:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catalogos generated by hbm2java
 */
public class Catalogos  implements java.io.Serializable {


     private int CId;
     private Categorias categorias;
     private String CNombre;
     private String CDirector;
     private String CActorPrin;
     private Integer CCantidad;
     private String CTipo;
     private Float CPrecAlqu;
     private Float CPrecComp;
     private Set detalleses = new HashSet(0);

    public Catalogos() {
    }

	
    public Catalogos(int CId) {
        this.CId = CId;
    }
    public Catalogos(int CId, Categorias categorias, String CNombre, String CDirector, String CActorPrin, Integer CCantidad, String CTipo, Float CPrecAlqu, Float CPrecComp, Set detalleses) {
       this.CId = CId;
       this.categorias = categorias;
       this.CNombre = CNombre;
       this.CDirector = CDirector;
       this.CActorPrin = CActorPrin;
       this.CCantidad = CCantidad;
       this.CTipo = CTipo;
       this.CPrecAlqu = CPrecAlqu;
       this.CPrecComp = CPrecComp;
       this.detalleses = detalleses;
    }
   
    public int getCId() {
        return this.CId;
    }
    
    public void setCId(int CId) {
        this.CId = CId;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getCNombre() {
        return this.CNombre;
    }
    
    public void setCNombre(String CNombre) {
        this.CNombre = CNombre;
    }
    public String getCDirector() {
        return this.CDirector;
    }
    
    public void setCDirector(String CDirector) {
        this.CDirector = CDirector;
    }
    public String getCActorPrin() {
        return this.CActorPrin;
    }
    
    public void setCActorPrin(String CActorPrin) {
        this.CActorPrin = CActorPrin;
    }
    public Integer getCCantidad() {
        return this.CCantidad;
    }
    
    public void setCCantidad(Integer CCantidad) {
        this.CCantidad = CCantidad;
    }
    public String getCTipo() {
        return this.CTipo;
    }
    
    public void setCTipo(String CTipo) {
        this.CTipo = CTipo;
    }
    public Float getCPrecAlqu() {
        return this.CPrecAlqu;
    }
    
    public void setCPrecAlqu(Float CPrecAlqu) {
        this.CPrecAlqu = CPrecAlqu;
    }
    public Float getCPrecComp() {
        return this.CPrecComp;
    }
    
    public void setCPrecComp(Float CPrecComp) {
        this.CPrecComp = CPrecComp;
    }
    public Set getDetalleses() {
        return this.detalleses;
    }
    
    public void setDetalleses(Set detalleses) {
        this.detalleses = detalleses;
    }




}


